-- Mason Manca
-- CPSC 321 Section 01
-- Dr.Bowers
-- 22 November 22

/*
************************** Main Relations **************************
Exercises( exercise_id, exercise_name, muscles_worked, desc, compound_or_accessory)
AllSplits( split_id, split_name, muscle_group_split, times_per_week, split_desc)
YourSplit( split_id, exercise_id, times_per_week, time_of_week, sets, reps )
ScientificResearch( exercise_id, muscles_worked, risk, reward, optimal_score, num_fibers )
Tips( exercise_id, exercise_name, tip_desc )
CompoundOrAccessory( exercise_id, compound_or_accessory, intensity, risk_val, reward_val)
BestForMuscleGroup( exercise_id, exercise_name, muscle_group, num_fibers, optimal_score)
UserWeekdaySplit(split_id, exercise_id, exercise_name, day_of_week enum('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'), sets, reps);
*/


-- -- -- INSERT statements:
-- inserting 30 unique/distinct exercises into Exercises table, following the schema and including chest, back, legs, arms, and shoulders
-- make sure they are unqiue values
INSERT INTO Exercises (exercise_id, exercise_name, muscles_worked, compound_or_accessory) VALUES
    (1, 'Barbell Bench Press', 'chest', 'compound'),
    (2, 'Dumbbell Fly', 'chest', 'accessory'),
    (3, 'Push-up', 'chest', 'compound'),
    (4, 'Pull-up', 'back', 'compound'),
    (5, 'Barbell Deadlift', 'back', 'compound'),
    (6, 'Dumbbell Row', 'back', 'compound'),
    (7, 'Barbell Squat', 'legs', 'compound'),
    (8, 'Lunge', 'legs', 'compound'),
    (9, 'Calf Raise', 'legs', 'accessory'),
    (10, 'Barbell Curl', 'arms', 'compound'),
    (11, 'Tricep Extension', 'arms', 'accessory'),
    (12, 'Dumbbell Hammer Curl', 'arms', 'compound'),
    (13, 'Tricep Dips', 'arms', 'compound'),
    (14, 'Shoulder Press', 'shoulders', 'compound'),
    (15, 'Lateral Raise', 'shoulders', 'accessory'),
    (16, 'Front Raise', 'shoulders', 'accessory'),
    (17, 'Rear Delt Fly', 'shoulders', 'accessory'),
    (18, 'Plank', 'abdominals', 'compound'),
    (19, 'Russian Twist', 'abdominals', 'compound'),
    (20, 'Side Plank', 'abdominals', 'compound'),
    (21, 'Mountain Climber', 'abdominals', 'compound'),
    (22, 'Bicycle Crunch', 'abdominals', 'compound'),
    (23, 'Leg Raise', 'abdominals', 'compound'),
    (24, 'Crunch', 'abdominals', 'compound'),
    (25, 'Barbell Shrug', 'traps', 'compound'),
    (26, 'Dumbbell Shrug', 'traps', 'compound'),
    (27, 'Barbell Shoulder Press', 'shoulders', 'compound'),
    (28, 'Dumbbell Shoulder Press', 'shoulders', 'compound'),
    (29, 'Barbell Bent Over Row', 'back', 'compound'),
    (30, 'Dumbbell Bent Over Row', 'back', 'compound'),
    (31, 'Barbell Upright Row', 'shoulders', 'compound');




    
-- insert 30 unique values into the Scientific Research table, following the schema provided:
-- ScientificResearch( exercise_id, muscles_worked, risk, reward, optimal_score, num_fibers )
INSERT INTO ScientificResearch VALUES
(1, 'chest', 3, 5, 8, 200),
(2, 'chest', 2, 4, 7, 150),
(3, 'chest', 2, 4, 7, 150),
(4, 'back', 4, 6, 9, 250),
(5, 'back', 5, 7, 10, 300),
(6, 'back', 3, 5, 8, 200),
(7, 'legs', 4, 6, 9, 250),
(8, 'legs', 3, 5, 8, 200),
(9, 'legs', 1, 3, 6, 100),
(10, 'arms', 2, 4, 7, 150),
(11, 'arms', 1, 3, 6, 100),
(12, 'arms', 2, 4, 7, 150),
(13, 'arms', 2, 4, 7, 150),
(14, 'shoulders', 3, 5, 8, 200),
(15, 'shoulders', 2, 4, 7, 150),
(16, 'shoulders', 3, 5, 8, 200),
(17, 'shoulders', 2, 4, 7, 150),
(18, 'abdominals', 2, 4, 7, 150),
(19, 'abdominals', 2, 4, 7, 150),
(20, 'abdominals', 1, 3, 6, 100),
(21, 'abdominals', 2, 4, 7, 150),
(22, 'abdominals', 2, 4, 7, 150),
(23, 'abdominals', 2, 4, 7, 150),
(24, 'abdominals', 2, 4, 7, 150),
(25, 'shoulders', 3, 5, 8, 200),
(26, 'shoulders', 2, 4, 7, 150),
(27, 'shoulders', 3, 5, 8, 200),
(28, 'shoulders', 2, 4, 7, 150),
(29, 'back', 4, 6, 9, 250),
(30, 'back', 5, 7, 10, 300),
(31, 'back', 3, 5, 8, 200);

-- insert 31 unique values into the BestForMuscleGroup table, following the schema provided and using the exercise_id and exercise_name values from the Exercise table:
-- BestForMuscleGroup( exercise_id, exercise_name, muscle_group, num_fibers, optimal_score)
INSERT INTO BestForMuscleGroup VALUES
    (1, 'Barbell Bench Press', 'chest', 5, 8),
    (2, 'Dumbbell Fly', 'chest', 3, 7),
    (3, 'Push-up', 'chest', 4, 9),
    (4, 'Pull-up', 'back', 6, 10),
    (5, 'Barbell Deadlift', 'back', 8, 10),
    (6, 'Dumbbell Row', 'back', 5, 9),
    (7, 'Barbell Squat', 'legs', 7, 8),
    (8, 'Lunge', 'legs', 4, 6),
    (9, 'Calf Raise', 'legs', 3, 5),
    (10, 'Barbell Curl', 'arms', 5, 8),
    (11, 'Tricep Extension', 'arms', 4, 7),
    (12, 'Dumbbell Hammer Curl', 'arms', 6, 9),
    (13, 'Tricep Dips', 'arms', 3, 6),
    (14, 'Shoulder Press', 'shoulders', 7, 10),
    (15, 'Lateral Raise', 'shoulders', 5, 8),
    (16, 'Front Raise', 'shoulders', 6, 9),
    (17, 'Rear Delt Fly', 'shoulders', 4, 7),
    (18, 'Plank', 'abdominals', 5, 8),
    (19, 'Russian Twist', 'abdominals', 4, 7),
    (20, 'Side Plank', 'abdominals', 3, 6),
    (21, 'Mountain Climber', 'abdominals', 6, 9),
    (22, 'Bicycle Crunch', 'abdominals', 5, 8),
    (23, 'Leg Raise', 'abdominals', 4, 7),
    (24, 'Crunch', 'abdominals', 3, 6),
    (25, 'Barbell Shrug', 'shoulders', 7, 10),
    (26, 'Dumbbell Shrug', 'shoulders', 5, 8),
    (27, 'Barbell Shoulder Press', 'shoulders', 6, 9),
    (28, 'Dumbbell Shoulder Press', 'shoulders', 4, 7),
    (29, 'Barbell Bent Over Row', 'back', 7, 10),
    (30, 'Dumbbell Bent Over Row', 'back', 5, 8),
    (31, 'Barbell Upright Row', 'shoulders', 6, 9);

-- insert 31 unique values into the Tips table, following the schema provided, and using the exercise_id and exercise_name values from the Exercise table:
-- Tips( exercise_id, exercise_name, tip_desc )
-- make sure to use different values for the tip_desc column than the exercise table, and have them correspond to the exercise_name and muscle group
INSERT INTO Tips VALUES 
    (1, 'Barbell Bench Press', 'Keep your elbows tucked in to your sides and your wrists straight. This will help you keep your shoulders back and your chest up.'),
    (2, 'Dumbbell Fly', 'Tuck in your lats when performing this exercise. When doing the movement focus on not feeling it in your shoulders.'),
    (3, 'Push-up', "Ensure that your arms are not too wide and are shoulder-width apart. Slowly descend to the bottom and then explode to the top."),
    (4, 'Pull-up', 'Perform the movement with the idea that youre trying to touch your chest to the bar. Contract your shoulder baldes with each rep.'),
    (5, 'Barbell Deadlift', "Don't forget to pull the slack out of the bar before each movement. Keep your back straight and your chest up."),
    (6, 'Dumbbell Row', 'Use a full range of motion and squeeze your shoulder blades together at the top of the movement.'),
    (7, 'Barbell Squat', 'Keep your feet hip-width apart and your weight on your heels, and avoid leaning forward too much.'),
    (8, 'Lunge', 'Keep your chest up and your front knee aligned with your front foot, and avoid letting your back knee touch the ground.'),
    (9, 'Calf Raise', 'Use a full range of motion and squeeze your calf muscles at the top of the movement.'),
    (10, 'Barbell Curl', 'Use a full range of motion and avoid swinging your body during the movement.'),
    (11, 'Tricep Extension', 'Keep your elbows close to your body and avoid locking out your elbows at the top of the movement.'),
    (12, 'Dumbbell Hammer Curl', 'Keep your elbows close to your body and avoid swinging your body during the movement.'),
    (13, 'Tricep Dips', 'Keep your elbows close to your body and avoid leaning too far forward.'),
    (14, 'Shoulder Press', 'Keep your wrists straight and your elbows at a 90-degree angle, and avoid leaning too far forward.'),
    (15, 'Lateral Raise', 'Use a full range of motion and squeeze your shoulder muscles at the top of the movement.'),
    (16, 'Front Raise', 'Use a full range of motion and avoid swinging your body during the movement.'),
    (17, 'Rear Delt Fly', 'Use a full range of motion and squeeze your shoulder muscles at the top of the movement.'),
    (18, 'Plank', 'Keep your body in a straight line and avoid sagging at the hips or raising your butt too high.'),
    (19, 'Russian Twist', 'Keep your feet off the ground and avoid leaning too far to one side.'),
    (20, 'Side Plank', 'Keep your body in a straight line and avoid sagging at the hips or raising your butt too high.'),
    (21, 'Mountain Climber', 'Keep your body in a straight line and avoid sagging at the hips or raising your butt too high.'),
    (22, 'Bicycle Crunch', 'Keep your lower back on the ground and avoid pulling on your neck.'),
    (23, 'Leg Raise', 'Keep your legs straight and your feet together, and avoid swinging your legs during the movement.'),
    (24, 'Crunch', 'Keep your hands behind your head and avoid pulling on your neck. Focus on contracting your abdominal muscles during the movement.'),
    (25, 'Barbell Shrug', 'Use a full range of motion and squeeze your shoulder muscles at the top of the movement.'),
    (26, 'Dumbbell Shrug', 'Use a full range of motion and squeeze your shoulder muscles at the top of the movement.'),
    (27, 'Barbell Shoulder Press', 'Keep your wrists straight and your elbows at a 90-degree angle, and avoid leaning too far forward.'),
    (28, 'Dumbbell Shoulder Press', 'Keep your wrists straight and your elbows at a 90-degree angle, and avoid leaning too far forward.'),
    (29, 'Barbell Bent Over Row', 'Keep your back straight and your chest up, and avoid rounding your lower back at the top of the movement.'),
    (30, 'Dumbbell Bent Over Row', 'Keep your back straight and your chest up, and avoid rounding your lower back at the top of the movement.'),
    (31, 'Barbell Upright Row', 'Keep your wrists straight and your elbows at a 90-degree angle, and avoid leaning too far forward.');


-- insert 31 unique values into the AllSplits table, following the schema provided:
-- also, make sure to use the exercise_id and exercise_name values from the Exercise table
-- AllSplits( split_id, split_name, muscle_group_split, times_per_week, split_desc)


INSERT INTO AllSplits VALUES 
    (1, 'Upper Body', 'chest, back, arms, shoulders', 3, 'This split focuses on exercises for the chest, back, arms, and shoulders.'),
    (2, 'Lower Body', 'legs, abs', 2, 'This split focuses on exercises for the legs and abs.'),
    (3, 'Full Body', 'chest, back, arms, shoulders, legs, abs', 3, 'This split focuses on exercises for the entire body.'),
    (4, 'Push/Pull', 'chest, arms, shoulders, back', 3, 'This split focuses on exercises that target pushing muscles (chest, arms, shoulders) and pulling muscles (back).'),
    (5, 'Legs/Abs', 'legs, abs', 2, 'This split focuses on exercises for the legs and abs.'),
    (6, 'Upper/Lower Body', 'chest, back, arms, shoulders, legs, abs', 3, 'This split divides the body into upper and lower body muscle groups.'),
    (7, 'Chest/Back', 'chest, back', 2, 'This split focuses on exercises for the chest and back.'),
    (8, 'Arms/Shoulders', 'arms, shoulders', 2, 'This split focuses on exercises for the arms and shoulders.'),
    (9, 'Legs/Shoulders', 'legs, shoulders', 2, 'This split focuses on exercises for the legs and shoulders.'),
    (10, 'Chest/Shoulders/Triceps', 'chest, shoulders, triceps', 2, 'This split focuses on exercises for the chest, shoulders, and triceps.'),
    (11, 'Back/Biceps', 'back, biceps', 2, 'This split focuses on exercises for the back and biceps.'),
    (12, 'Lower Body/Abs', 'legs, abs', 2, 'This split focuses on exercises for the legs and abs.'),
    (13, 'Chest/Back/Abs', 'chest, back, abs', 2, 'This split focuses on exercises for the chest, back, and abs.'),
    (14, 'Chest/Arms/Abs', 'chest, arms, abs', 2, 'This split focuses on exercises for the chest, arms, and abs.'),
    (15, 'Back/Shoulders/Abs', 'back, shoulders, abs', 2, 'This split focuses on exercises for the back, shoulders, and abs.'),
    (16, 'Legs/Chest/Abs', 'legs, chest, abs', 2, 'This split focuses on exercises for the legs, chest, and abs.'),
    (17, 'Legs/Back/Abs', 'legs, back, abs', 2, 'This split focuses on exercises for the legs, back, and abs.'),
    (18, 'Chest/Triceps/Abs', 'chest, triceps, abs', 2, 'This split focuses on exercises for the chest, triceps, and abs.'),
    (19, 'Back/Biceps/Abs', 'back, biceps, abs', 2, 'This split focuses on exercises for the back, biceps, and abs.'),
    (20, 'Shoulders/Triceps/Abs', 'shoulders, triceps, abs', 2, 'This split focuses on maximizing the width of your proportions.'),
    (21, 'Upper Body/Lower Body', 'chest, back, arms, shoulders, legs, abs', 3, 'This split divides the body into upper and lower body muscle groups.'),
    (22, 'Chest/Back/Arms', 'chest, back, arms', 3, 'This split focuses on exercises for the chest, back, and arms.'),
    (23, 'Legs/Abs/Arms', 'legs, abs, arms', 3, 'This split focuses on exercises for the legs, abs, and arms.'),
    (24, 'Full Body/Abs', 'chest, back, arms, shoulders, legs, abs', 4, 'This split focuses on exercises for the entire body and abs.'),
    (25, 'Chest/Back/Shoulders/Abs', 'chest, back, shoulders, abs', 4, 'This split focuses on exercises for the chest, back, shoulders, and abs.'),
    (26, 'Chest/Arms/Shoulders/Abs', 'chest, arms, shoulders, abs', 4, 'This split focuses on exercises for the chest, arms, shoulders, and abs.'),
    (27, 'Back/Arms/Shoulders/Abs', 'back, arms, shoulders, abs', 4, 'This split focuses on exercises for the back, arms, shoulders, and abs.'),
    (28, 'Shoulders/Arms/Abs', 'shoulders, arms, abs', 3, 'This split focuses on exercises for the shoulders, arms, and abs.'),
    (29, 'Legs/Chest/Back/Abs', 'legs, chest, back, abs', 4, 'This split focuses on exercises for the legs, chest, back, and abs.'),
    (30, 'Upper Body/Lower Body/Abs', 'chest, back, arms, shoulders, legs, abs', 4, 'This split divides the body into upper and lower body muscle groups and focuses on exercises for the abs.'),
    (31, 'Half Push/Pull Half Arnold', 'chest, back, arms, shoulders, legs, abs', 4, 'This is perhaps the best split out there, properly exhausting each muscle group!');


-- insert 30 values into the CompoundOrAccessory table, following the schema provided
-- and using the exercise_id values from the Exercise table
-- CompoundOrAccessory( exercise_id, compound_or_accessory, intensity, risk_val, reward_val)

INSERT INTO CompoundOrAccessory (exercise_id, exercise_name, compound_or_accessory, risk_val, reward_val) VALUES
  (1, 'Barbell Bench Press', 'compound', 5, 8),
  (2, 'Dumbbell Fly', 'accessory', 3, 7),
  (3, 'Push-up', 'compound', 4, 9),
  (4, 'Pull-up', 'compound', 6, 10),
  (5, 'Barbell Deadlift', 'compound', 8, 10),
  (6, 'Dumbbell Row', 'compound', 5, 9),
  (7, 'Barbell Squat', 'compound', 7, 8),
  (8, 'Lunge', 'accessory', 4, 6),
  (9, 'Calf Raise', 'accessory', 3, 5),
  (10, 'Barbell Curl', 'accessory', 5, 8),
  (11, 'Tricep Extension', 'accessory', 4, 7),
  (12, 'Dumbbell Hammer Curl', 'accessory', 6, 9),
  (13, 'Tricep Dips', 'compound', 3, 6),
  (14, 'Shoulder Press', 'compound', 7, 10),
  (15, 'Lateral Raise', 'accessory', 5, 8),
  (16, 'Front Raise', 'accessory', 6, 9),
  (17, 'Rear Delt Fly', 'accessory', 4, 7),
  (18, 'Plank', 'compound', 5, 8),
  (19, 'Russian Twist', 'accessory', 4, 7),
  (20, 'Side Plank', 'accessory', 3, 6),
  (21, 'Mountain Climber', 'compound', 6, 9),
  (22, 'Bicycle Crunch', 'accessory', 5, 8),
  (23, 'Leg Raise', 'accessory', 4, 7),
  (24, 'Crunch', 'compound', 3, 6),
  (25, 'Barbell Shrug', 'compound', 7, 10),
  (26, 'Dumbbell Shrug', 'compound', 5, 8),
  (27, 'Barbell Shoulder Press', 'compound', 6, 9),
  (28, 'Dumbbell Shoulder Press', 'compound', 4, 7),
  (29, 'Barbell Bent Over Row', 'compound', 7, 10),
  (30, 'Dumbbell Bent Over Row', 'compound', 5, 8),
  (31, 'Barbell Upright Row', 'compound', 6, 9);

INSERT INTO UserWeekdaySplit(split_id, exercise_id, exercise_name, day_of_week, sets, reps)
VALUES
(1, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(1, 2, 'Dumbbell Fly', 'Monday', 3, 12),
(1, 3, 'Push-up', 'Monday', 3, 10),
(1, 4, 'Pull-up', 'Tuesday', 3, 8),
(1, 5, 'Barbell Deadlift', 'Tuesday', 3, 5),
(1, 6, 'Dumbbell Row', 'Tuesday', 3, 10),
(1, 7, 'Barbell Squat', 'Tuesday', 3, 8),
(1, 8, 'Lunge', 'Tuesday', 3, 10),
(1, 9, 'Calf Raise', 'Tuesday', 3, 12),
(1, 10, 'Barbell Curl', 'Wednesday', 3, 8),
(1, 11, 'Tricep Extension', 'Wednesday', 3, 10),
(1, 12, 'Dumbbell Hammer Curl', 'Wednesday', 3, 12),

(2, 13, 'Tricep Dips', 'Wednesday', 3, 10),
(2, 14, 'Shoulder Press', 'Thursday', 3, 8),
(2, 15, 'Lateral Raise', 'Thursday', 3, 10),
(2, 16, 'Front Raise', 'Thursday', 3, 12),
(2, 17, 'Rear Delt Fly', 'Thursday', 3, 10),
(2, 18, 'Plank', 'Friday', 3, 60),
(2, 19, 'Russian Twist', 'Friday', 3, 30),
(2, 20, 'Side Plank', 'Friday', 3, 30),
(2, 21, 'Mountain Climber', 'Friday', 3, 30),
(2, 22, 'Bicycle Crunch', 'Friday', 3, 30),
(2, 23, 'Leg Raise', 'Friday', 3, 30),
(2, 24, 'Crunch', 'Friday', 3, 30),
(2, 1, 'Barbell Bench Press', 'Monday', 4, 12),
(2, 2, 'Dumbbell Fly', 'Monday', 3, 12),
(2, 3, 'Push-up', 'Monday', 3, 10),

(3, 25, 'Barbell Shrug', 'Thursday', 3, 8),
(3, 26, 'Dumbbell Shrug', 'Thursday', 3, 8),
(3, 27, 'Barbell Shoulder Press', 'Saturday', 3, 8),
(3, 28, 'Dumbbell Shoulder Press', 'Saturday', 3, 8),
(3, 29, 'Barbell Bent Over Row', 'Tuesday', 3, 8),
(3, 30, 'Dumbbell Bent Over Row', 'Tuesday', 3, 8),
(3, 31, 'Barbell Upright Row', 'Saturday', 3, 8),
(3, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(3, 2, 'Dumbbell Fly', 'Monday', 3, 12),
(3, 3, 'Push-up', 'Monday', 3, 10),
(3, 4, 'Pull-up', 'Tuesday', 3, 8),
(3, 5, 'Barbell Deadlift', 'Tuesday', 3, 5),
(3, 6, 'Dumbbell Row', 'Sunday', 3, 10),
(3, 7, 'Barbell Squat', 'Sunday', 3, 8),
(3, 8, 'Lunge', 'Thursday', 3, 10),
(3, 9, 'Calf Raise', 'Sunday', 3, 12),
(3, 10, 'Barbell Curl', 'Wednesday', 3, 8),
(3, 11, 'Tricep Extension', 'Wednesday', 3, 10),
(3, 12, 'Dumbbell Hammer Curl', 'Wednesday', 3, 12),

(4, 13, 'Tricep Dips', 'Wednesday', 3, 10),
(4, 14, 'Shoulder Press', 'Thursday', 3, 8),
(4, 15, 'Lateral Raise', 'Thursday', 3, 10),
(4, 16, 'Front Raise', 'Thursday', 3, 12),
(4, 18, 'Plank', 'Friday', 3, 60),
(4, 19, 'Russian Twist', 'Friday', 3, 30),
(4, 20, 'Side Plank', 'Friday', 3, 30),
(4, 21, 'Mountain Climber', 'Friday', 3, 30),
(4, 22, 'Bicycle Crunch', 'Friday', 3, 30),   
(4, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(4, 2, 'Dumbbell Fly', 'Monday', 3, 12),
(4, 3, 'Push-up', 'Monday', 3, 10),
(4, 4, 'Pull-up', 'Tuesday', 3, 8),
(4, 5, 'Barbell Deadlift', 'Tuesday', 3, 5),
(4, 6, 'Dumbbell Row', 'Tuesday', 3, 10),
(4, 7, 'Barbell Squat', 'Tuesday', 3, 8),
(4, 10, 'Barbell Curl', 'Wednesday', 3, 8),

(5, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(5, 2, 'Dumbbell Fly', 'Monday', 3, 7),
(5, 3, 'Push-up', 'Monday', 4, 9),
(5, 4, 'Pull-up', 'Monday', 6, 10),
(5, 5, 'Barbell Deadlift', 'Monday', 8, 10),
(5, 6, 'Dumbbell Row', 'Monday', 5, 9),
(5, 7, 'Barbell Squat', 'Wednesday', 3, 8),
(5, 8, 'Lunge', 'Wednesday', 3, 6),
(5, 9, 'Calf Raise', 'Wednesday', 3, 5),
(5, 14, 'Shoulder Press', 'Wednesday', 3, 10),
(5, 15, 'Lateral Raise', 'Wednesday', 3, 8),
(5, 16, 'Front Raise', 'Wednesday', 3, 9),
(5, 18, 'Plank', 'Friday', 3, 8),
(5, 19, 'Russian Twist', 'Friday', 3, 7),
(5, 20, 'Side Plank', 'Friday', 3, 6),
(5, 21, 'Mountain Climber', 'Friday', 3, 9),
(5, 22, 'Bicycle Crunch', 'Friday', 3, 8),
(5, 23, 'Leg Raise', 'Friday', 3, 7),

(6, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(6, 2, 'Dumbbell Fly', 'Monday', 3, 7),
(6, 3, 'Push-up', 'Monday', 3, 9),
(6, 4, 'Pull-up', 'Wednesday', 3, 10),
(6, 5, 'Barbell Deadlift', 'Wednesday', 3, 10),
(6, 6, 'Dumbbell Row', 'Wednesday', 3, 9),
(6, 7, 'Barbell Squat', 'Friday', 3, 8),
(6, 8, 'Lunge', 'Friday', 3, 6),
(6, 9, 'Calf Raise', 'Friday', 3, 5),
(6, 14, 'Shoulder Press', 'Wednesday', 3, 10),
(6, 15, 'Lateral Raise', 'Wednesday', 3, 8),
(6, 16, 'Front Raise', 'Wednesday', 3, 9),
(6, 18, 'Plank', 'Friday', 3, 8),
(6, 19, 'Russian Twist', 'Friday', 3, 7),
(6, 20, 'Side Plank', 'Friday', 3, 6),
(6, 21, 'Mountain Climber', 'Friday', 3, 9),
(6, 22, 'Bicycle Crunch', 'Friday', 3, 8),
(6, 23, 'Leg Raise', 'Friday', 3, 7),

(7, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(7, 2, 'Dumbbell Fly', 'Monday', 3, 7),
(7, 3, 'Push-up', 'Monday', 3, 9),
(7, 4, 'Pull-up', 'Wednesday', 3, 10),
(7, 5, 'Barbell Deadlift', 'Wednesday', 3, 10),
(7, 6, 'Dumbbell Row', 'Wednesday', 3, 9),
(7, 7, 'Barbell Squat', 'Friday', 3, 8),
(7, 8, 'Lunge', 'Friday', 3, 6),
(7, 9, 'Calf Raise', 'Friday', 3, 5),

(8, 10, 'Barbell Curl', 'Monday', 5, 8),
(8, 11, 'Tricep Extension', 'Monday', 4, 7),
(8, 12, 'Dumbbell Hammer Curl', 'Monday', 6, 9),
(8, 13, 'Tricep Dips', 'Monday', 3, 6),
(8, 14, 'Shoulder Press', 'Wednesday', 7, 10),
(8, 15, 'Lateral Raise', 'Wednesday', 5, 8),
(8, 16, 'Front Raise', 'Wednesday', 6, 9),
(8, 17, 'Rear Delt Fly', 'Wednesday', 4, 7),
(8, 25, 'Barbell Shrug', 'Friday', 7, 10),
(8, 26, 'Dumbbell Shrug', 'Friday', 5, 8),
(8, 27, 'Barbell Shoulder Press', 'Friday', 6, 9),
(8, 28, 'Dumbbell Shoulder Press', 'Friday', 4, 7),

(9, 7, 'Barbell Squat', 'Monday', 7, 8),
(9, 8, 'Lunge', 'Monday', 4, 6),
(9, 9, 'Calf Raise', 'Monday', 3, 5),
(9, 14, 'Shoulder Press', 'Monday', 7, 10),
(9, 15, 'Lateral Raise', 'Wednesday', 5, 8),
(9, 16, 'Front Raise', 'Wednesday', 6, 9),
(9, 17, 'Rear Delt Fly', 'Wednesday', 4, 7),
(9, 25, 'Barbell Shrug', 'Friday', 7, 10),
(9, 26, 'Dumbbell Shrug', 'Friday', 5, 8),
(9, 27, 'Barbell Shoulder Press', 'Friday', 6, 9),
(9, 28, 'Dumbbell Shoulder Press', 'Friday', 4, 7),
(9, 29, 'Barbell Bent Over Row', 'Friday', 7, 10),

(10, 10, 'Barbell Curl', 'Monday', 5, 8),
(10, 11, 'Tricep Extension', 'Monday', 4, 7),
(10, 12, 'Dumbbell Hammer Curl', 'Monday', 6, 9),
(10, 13, 'Tricep Dips', 'Monday', 3, 6),
(10, 31, 'Barbell Upright Row', 'Wednesday', 6, 9),
(10, 16, 'Front Raise', 'Wednesday', 6, 9),
(10, 17, 'Rear Delt Fly', 'Wednesday', 4, 7),
(10, 11, 'Tricep Extension', 'Wednesday', 4, 7),
(10, 10, 'Barbell Curl', 'Friday', 5, 8),
(10, 12, 'Dumbbell Hammer Curl', 'Friday', 6, 9),
(10, 13, 'Tricep Dips', 'Friday', 3, 6),
(10, 31, 'Barbell Upright Row', 'Friday', 6, 9),
    
(11, 7, 'Barbell Squat', 'Monday', 7, 8),
(11, 8, 'Lunge', 'Monday', 4, 6),
(11, 9, 'Calf Raise', 'Monday', 3, 5),
(11, 14, 'Shoulder Press', 'Monday', 7, 10),
(11, 15, 'Lateral Raise', 'Wednesday', 5, 8),
(11, 16, 'Front Raise', 'Wednesday', 6, 9),
(11, 17, 'Rear Delt Fly', 'Wednesday', 4, 7),
(11, 25, 'Barbell Shrug', 'Friday', 7, 10),
(11, 26, 'Dumbbell Shrug', 'Friday', 5, 8),
(11, 27, 'Barbell Shoulder Press', 'Friday', 6, 9),
(11, 28, 'Dumbbell Shoulder Press', 'Friday', 4, 7),
(11, 29, 'Barbell Bent Over Row', 'Friday', 7, 10),

(12, 10, 'Barbell Curl', 'Monday', 5, 8),
(12, 11, 'Tricep Extension', 'Monday', 4, 7),
(12, 12, 'Dumbbell Hammer Curl', 'Monday', 6, 9),
(12, 13, 'Tricep Dips', 'Monday', 3, 6),
(12, 31, 'Barbell Upright Row', 'Wednesday', 6, 9),
(12, 16, 'Front Raise', 'Wednesday', 6, 9),
(12, 17, 'Rear Delt Fly', 'Wednesday', 4, 7),
(12, 11, 'Tricep Extension', 'Wednesday', 4, 7),
(12, 10, 'Barbell Curl', 'Friday', 5, 8),
(12, 12, 'Dumbbell Hammer Curl', 'Friday', 6, 9),
(12, 13, 'Tricep Dips', 'Friday', 3, 6),
(12, 31, 'Barbell Upright Row', 'Friday', 5,8),

(13, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(13, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(13, 4, 'Pull-up', 'Monday', 4, 9),
(13, 24, 'Crunch', 'Monday', 2, 20),
(13, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(13, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(13, 4, 'Pull-up', 'Wednesday', 4, 9),
(13, 24, 'Crunch', 'Wednesday', 2, 20),

(14, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(14, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(14, 4, 'Pull-up', 'Monday', 4, 9),
(14, 24, 'Crunch', 'Monday', 2, 20),
(14, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(14, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(14, 4, 'Pull-up', 'Wednesday', 4, 9),
(14, 24, 'Crunch', 'Wednesday', 2, 20),

(15, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(15, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(15, 4, 'Pull-up', 'Tuesday', 4, 9),
(15, 24, 'Crunch', 'Monday', 2, 20),
(15, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(15, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),

(16, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(16, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(16, 4, 'Pull-up', 'Monday', 4, 9),
(16, 24, 'Crunch', 'Monday', 2, 20),
(16, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(16, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(16, 4, 'Pull-up', 'Wednesday', 4, 9),
(16, 24, 'Crunch', 'Wednesday', 2, 12),

(17, 4, 'Pull-up', 'Monday', 4,9),
(17, 24, 'Crunch', 'Monday', 2, 20),
(17, 4, 'Pull-up', 'Wednesday', 4, 9),
(17, 24, 'Crunch', 'Wednesday', 2, 20),
(17, 31, 'Barbell Upright Row','Monday', 4, 12),

(18, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(18, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(18, 4, 'Pull-up', 'Monday', 2, 20),
(18, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(18, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(18, 4, 'Pull-up', 'Wednesday', 2, 20),

(19, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(19, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(19, 4, 'Pull-up', 'Tuesday', 2, 20),
(19, 1, 'Barbell Bench Press', 'Tuesday', 3, 8),
(19, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(19, 4, 'Pull-up', 'Wednesday', 2, 20),
(19, 31, 'Barbell Upright Row','Thursday', 4, 12),

(20, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(20, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(20, 4, 'Pull-up', 'Monday', 2, 20),
(20, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(20, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(20, 4, 'Pull-up', 'Wednesday', 2, 20),

(21, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(21, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(21, 4, 'Pull-up', 'Tuesday', 2, 20),
(21, 1, 'Barbell Bench Press', 'Tuesday',3, 8),
(21, 19, 'Russian Twist','Wednesday', 4, 12),
(21, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(21, 4, 'Pull-up', 'Wednesday', 2, 20),

(22, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(22, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(22, 4, 'Pull-up', 'Monday', 2, 20),
(22, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(22, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(22, 4, 'Pull-up', 'Wednesday', 2, 20),

(23, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(23, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(23, 4, 'Pull-up', 'Monday', 2, 20),
(23, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(23, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(23, 4, 'Pull-up', 'Wednesday', 2, 20),

(24, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(24, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(24, 4, 'Pull-up', 'Monday', 2, 20),
(24, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(24, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(24, 4, 'Pull-up', 'Wednesday', 2, 20),

(25, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(25, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(25, 4, 'Pull-up', 'Monday', 2, 20),
(25, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(25, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(25, 4, 'Pull-up', 'Wednesday', 2, 20),

(26, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(26, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(26, 4, 'Pull-up', 'Monday', 2, 20),
(26, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(26, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(26, 4, 'Pull-up', 'Wednesday', 2, 20),

(27, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(27, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(27, 3, 'Push-up', 'Monday', 2, 20),
(27, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(27, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(27, 3, 'Push-up', 'Wednesday', 5, 15),
(27, 14, 'Shoulder Press', 'Thursday', 3,15),
(27, 15, 'Lateral Raise', 'Thursday', 3, 12),
(27, 16, 'Front Raise', 'Thursday', 3, 10),
(27, 26, 'Dumbell Shrug', "Thursday", 2, 15),

(28, 7, 'Barbell Squat','Monday', 5, 10),
(28, 9, 'Calf Raise', 'Monday', 3, 12),
(28, 10, 'Leg Extension', 'Monday', 3, 10),
(28, 11, 'Leg Curl', 'Monday', 3, 10),
(28, 12, 'Lunge', 'Monday', 3, 10),
(28, 13, 'Leg Press', 'Monday', 3, 10),
(28, 7, 'Barbell Squat','Wednesday', 5, 10),
(28, 9, 'Calf Raise', 'Wednesday', 3, 12),
(28, 10, 'Leg Extension', 'Wednesday', 3, 10),
(28, 11, 'Leg Curl', 'Wednesday', 3, 10),
(28, 12, 'Lunge', 'Wednesday', 3, 10),
(28, 13, 'Leg Press', 'Wednesday', 3, 10),
(28, 14, 'Shoulder Press', 'Thursday', 3,15),
(28, 15, 'Lateral Raise', 'Thursday', 3, 12),
(28, 16, 'Front Raise', 'Thursday', 3, 10),
(28, 26, 'Dumbell Shrug', "Thursday", 2, 15),

(29, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(29, 2, 'Dumbbell Flyes', 'Monday', 3, 10),
(29, 3, 'Push-up', 'Monday', 2, 20),
(29, 1, 'Barbell Bench Press', 'Wednesday', 3, 8),
(29, 2, 'Dumbbell Flyes', 'Wednesday', 3, 10),
(29, 3, 'Push-up', 'Wednesday', 5, 15),
(29, 14, 'Shoulder Press', 'Thursday', 3,15),
(29, 15, 'Lateral Raise', 'Thursday', 3, 12),
(29, 16, 'Front Raise', 'Thursday', 3, 10),
(29, 26, 'Dumbell Shrug', "Thursday", 2, 15),

(30, 1, 'Barbell Bench Press', 'Monday', 3, 8),
(30, 2, 'Dumbbell Fly', 'Monday', 3, 7),
(30, 3, 'Push-up', 'Monday', 3, 9),
(30, 4, 'Pull-up', 'Monday', 3, 10),
(30, 5, 'Barbell Deadlift', 'Monday', 3, 10),
(30, 6, 'Dumbbell Row', 'Monday', 3, 9),
(30, 7, 'Barbell Squat', 'Wednesday', 3, 8),
(30, 8, 'Lunge', 'Wednesday', 3, 6),
(30, 9, 'Calf Raise', 'Wednesday', 3, 5),
(30, 14, 'Shoulder Press', 'Wednesday', 3, 10),
(30, 15, 'Lateral Raise', 'Wednesday', 3, 8),
(30, 16, 'Front Raise', 'Wednesday', 3, 9),
(30, 18, 'Plank', 'Friday', 3, 8),
(30, 19, 'Russian Twist', 'Friday', 3, 7),
(30, 20, 'Side Plank', 'Friday', 3, 6),
(30, 21, 'Mountain Climber', 'Friday', 3, 9),
(30, 22, 'Bicycle Crunch', 'Friday', 3, 8),
(30, 23, 'Leg Raise', 'Friday', 3, 7),

(31, 1, 'Barbell Bench Press', 'Monday', 5, 8),
(31, 4, 'Pull-up', 'Monday', 6, 10),
(31, 10, 'Barbell Curl', 'Monday', 5, 8),
(31, 15, 'Lateral Raise', 'Monday', 5, 8),
(31, 3, 'Push-up', 'Wednesday', 4, 9),
(31, 6, 'Dumbbell Row', 'Wednesday', 5, 9),
(31, 11, 'Tricep Extension', 'Wednesday', 4, 7),
(31, 16, 'Front Raise', 'Wednesday', 6, 9),
(31, 2, 'Dumbbell Fly', 'Friday', 3, 7),
(31, 5, 'Barbell Deadlift', 'Friday', 8, 10),
(31, 13, 'Tricep Dips', 'Friday', 3, 6),
(31, 17, 'Rear Delt Fly', 'Friday', 4, 7);
